version: '3.8'

services:
  lert:
    build: ./
    command: pipenv run gunicorn LERT.wsgi:app
    volumes: 
      - ./:/usr/src/LERT-backend
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db2
      
  db2:
    image: ibmcom/db2:11.5.6.0a
    privileged: true
    ports:
      - 50000:50000
    env_file:
      - ./.env
    volumes:
      - db2_data:/var/lib/db2/data/


volumes:
  db2_data:
