name: Deploy to Cloud Foundry
on:
  push:
    branches: [dev]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jhunt/cf-push@v1
        with:
          api:      http://api.us-south.cf.cloud.ibm.com
          org:      ${{ secrets.CF_ORG }}
          space:    Development
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          manifest: manifest.yml
          validate: false
